### ISSUE TITLE
[BUG] Missing first instance of matched pause regex "^M601"

### ISSUE THREAD

**Issue by puterboy** [eyal0/OctoPrint-TimeToFilament#31]
I modeled new routines "TIme to Next Pause" and "Time of Next Pause" on the corresponding functions for filament changes.
The change was trivial, merely replacing "^M600"  with "^M601" and changing the relevant description text.

However, TImeToFilament seems to ignore the first pause (displaying nothing).
If there are more than one pauses, then after the first pause is resumed, TimeToFilament identifies and displays subsequent pause times correctly.

In contrast, for "Time to Next Filament Change", all filament changes are identified correctly.

Grepping through the gcode, there are indeed the right number and placement of "M601" commands.

Scratching my head at why TimeToFilament is ignoring the first pause while working ok with the first filament change code despite the fact that the configuration difference is so trivial.

The relevant portion of my config.yaml now looks like:
```
TimeToFilament:
    displayLines:
    - description: Time to Next Layer
      enabled: true
      format: Next layer in <b>${formatDuration(this.progress.printTimeLeft - this.plugins.TimeToFilament["^;LAYER_CHANGE"].timeLeft)}</b>
      regex: ^;LAYER_CHANGE
    - description: Time to Next Filament Change
      enabled: true
      format: Filament change in <b>${formatDuration(this.progress.printTimeLeft -
        this.plugins.TimeToFilament["^M600"].timeLeft)}</b>
      regex: ^M600
    - description: Time of Next Filament Change
      enabled: true
      format: Filament change at <b>${new Date(Date.now() + (this.progress.printTimeLeft
        - this.plugins.TimeToFilament["^M600"].timeLeft)*1000).toLocaleTimeString([],
        {hour12:false})}</b>
      regex: ^M600
    - description: Time to Next Pause
      enabled: true
      format: Pause in <b>${formatDuration(this.progress.printTimeLeft - this.plugins.TimeToFilament["^M601"].timeLeft)}</b>
      regex: ^M601
    - description: Time of Next Pause
      enabled: true
      format: Pause at <b>${new Date(Date.now() + (this.progress.printTimeLeft - this.plugins.TimeToFilament["^M601"].timeLeft)*1000).toLocaleTimeString([],
        {hour12:false})}</b>
      regex: ^M601
```
